###
POST http://localhost:9000/api/did/ HTTP/1.1
content-type: application/json

{
    "companyName": "Kukulu",
    "content": {
        "author": "Bao Bao",
        "dateCreated": "10-10-2021",
        "text": "This is a private document 2."
    }
}

###
POST http://localhost:8080/api/update-did/ HTTP/1.1
content-type: application/json

{
    "companyName": "Kukulu",
    "fileName": "ffff_gggg_hhhh_0000",
    "content": {
        "author": "Bao Bao",
        "dateCreated": "10-10-2021",
        "text": "This is a private document (updated)."
    }
}

###
GET http://localhost:8080/api/get-all-did/ HTTP/1.1
content-type: application/json

{
    "companyName": "Kukulu"
}

###
GET http://localhost:8080/api/get-did/ HTTP/1.1
content-type: application/json

{
    "companyName": "Kukulu",
    "fileName": "ffff_gggg_hhhh_0000"
}

###
DELETE http://localhost:8080/api/delete-did/ HTTP/1.1
content-type: application/json

{
    "companyName": "Kukulu",
    "fileName": "ffff_gggg_hhhh_2222"
}

###
GET https://petstore.swagger.io/v2/store/inventory HTTP/1.1
Content-Type: application/json